import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <div className='relative flex min-h-[86.1vh] flex-col justify-between overflow-x-clip scroll-smooth md:overflow-y-visible'>
          {children}
          <footer className="relative z-30 w-full px-6 bg-zinc-900 text-white">
  <div className="flex flex-row justify-between border-b border-zinc-800 bg-zinc-900 py-12 text-white transition-colors duration-150">
  <div className="col-span-1 lg:col-span-2 text-white">
  <a className="flex flex-initial items-center font-bold md:mr-24" href="/">
  <span className="mb-6">
  <div className="flex flex-row items-center gap-1">
  {/* <Image alt="Chathero" loading="lazy" width="32" height="32" decoding="async" data-nimg="1" className="aspect-square rounded-lg" style="color:transparent" src="/images/chathero-logo.svg"> */}
    <span className="hidden text-lg font-normal md:block text-white">Chathero</span></div></span></a><a className="block text-sm " href="/privacy">Privacy Policy</a>
    <a className="block text-sm " href="/terms">Terms of Service</a><button className="items-center justify-center whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-80 dark:hover:bg-zinc-800 dark:hover:text-zinc-50 h-7 rounded-md text-sm p-0 block w-full text-left hover:bg-inherit hover:text-inherit" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="radix-:r0:" data-state="closed">Cookie Preferences</button></div><div className="col-span-1 flex items-start text-black lg:col-span-6 lg:justify-end"><div className="flex h-10 items-center space-x-6"><a aria-label="LinkedIn Account" target="_blank" href="https://www.linkedin.com/company/chathero-co"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="text-white"><path fill-rule="evenodd" clip-rule="evenodd" d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" fill="currentColor"></path></svg></a></div></div></div><div className="py-6  text-black"><a href="/help"><button className="inline-flex items-center justify-center text-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-80 shadow dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/90 h-9 w-auto whitespace-nowrap rounded border bg-inherit px-2 py-1 font-semibold border-zinc-800 text-white hover:bg-zinc-800 hover:text-white">Contact Support</button></a></div>
  </footer>
        </div>
        
      </body>
    </html>
  )
}
